apiVersion: argoproj.io/v1alpha1
kind: Application #https://www.youtube.com/watch?v=MeU5_k9ssrs
metadata:
  name: myapp-application
  namespace: argocd # IMPORTANT: the same name of argo CD namespace. Don't change it
spec:
  project: default #https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
  source:
    repoURL: https://github.com/ma-sharifi/prometheus-k8s-spring.git
    targetRevision: HEAD
    path: prome2
  destination:
    server: https://kubernetes.default.svc
    namespace: prome2
  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true # create namespace automatically
    automated:
      selfHeal: true #undo any manual change in cluster
      prune: true