apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app-service-monitor
  labels:
    serviceMonitorSelector: prometheus
    monitoring: prometheus
#  namespace: example-app
    team: frontend
spec:
  endpoints:
    - interval: 30s
    - port: web    # is the same as  targetPort: 8080, cause you can see in kbernetes the post is:  web:8080►0
#      targetPort: 8080
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: "example-app"
  namespaceSelector:
    matchNames:
      - example-app