apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app-service-monitor
  labels:
    team: frontend
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: example-app
  namespaceSelector:
    matchNames:
      - monitoring
#  endpoints:
#    - port: web
