---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: picher/prometheus-k8s-spring:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
#            - name: http
#              containerPort: 8080
#            - name: http-metrics
#              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m
