---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: myapp-prom
  labels:
    app: myapp-monitoring
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app: myapp
