---
apiVersion: v1
kind: Service
metadata:
  name: myapp-prom-service
  namespace: staging
  labels:
    app: myapp
spec:
#  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: web
      port: 8080
#    - name: http-metrics
#      port: 8080
#      targetPort: http-metrics

