---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-service-monitor
  namespace: staging
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: web
#  endpoints:
#    - port: http-metrics
#      path: /actuator/prometheus

