apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server-metrics-service-monitor
  labels:
    serviceMonitorSelector: prometheus
    monitoring: prometheus
    team: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  endpoints:
    - port: metrics
  namespaceSelector:  #It uses the namespaceSelector to specify the Kubernetes Namespace in which we wish to locate the Service
    matchNames:
      - argocd # VERY IMPORTANT