apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics-service-monitor
  labels:
    serviceMonitorSelector: prometheus
    monitoring: prometheus
    team: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "argocd-server-metrics" # <- app.kubernetes.io/name=argocd-server-metrics
  endpoints:
  - interval: 30s
  - port: metrics    # <-  Port:metrics  8083/TCP