apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-applicationset-controller-metrics-service-monitor
  labels:
    serviceMonitorSelector: prometheus
    monitoring: prometheus
    team: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  endpoints:
    - port: metrics # Ports in Kuber is: webhook:7000►0 metrics:8080►0
  namespaceSelector: #It uses the namespaceSelector to specify the Kubernetes Namespace in which we wish to locate the Service
    matchNames:
      - argocd # VERY IMPORTANT