apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
#  namespace: prome3-> It will read from application->spec.destination.namespace:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: picher/prometheus-k8s-spring:latest
          ports:
            - name: web
              containerPort: 8080