apiVersion: rbac.authorization.k8s.io/v1 #https://stackoverflow.com/questions/73062343/failed-to-list-v1-pod-pods-is-forbidden-user-systemserviceaccountmonitorin
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: prome3