apiVersion: monitoring.coreos.com/v1
kind: Prometheus #describes the desired state of a Prometheus deployment
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true