apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector: # selects all the Pods with the app label having the example-app value.
    app: example-app
  ports:
    - name: web
      port: 8080 # specifies the port on which the metrics are exposed.