apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  namespaceSelector: prome3
  selector:
    matchLabels:
      app: example-app
  endpoints:
    - interval: 30s
    - port: web
      path: /actuator/prometheus